// Generated by duckwright from history.json. Review before committing:
// recorded code contains everything the agent typed, passwords included.
import { test, expect } from '@playwright/test';

test("press and shoot", async ({ page }) => {
  await page.goto('https://example.com/form');
  // Press Enter
  await page.keyboard.press('Enter');
  await a;
  await b;
  await c;
  await expect(page.getByText('Hello, Linh!')).toHaveText("Hello, Linh!");
});
