import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";

import { CLOSE_TAB_HELPER, ExportError, NO_ASSERTIONS, SELECT_TAB_HELPER, SPEC_NAME, TOTP_HELPER, TOTP_IMPORT, exportRun, loadHistory, renderSpec, stateBlock } from "../src/export.ts";
import type { HistoryData } from "../src/export.ts";
import { ROOT, tmpDir } from "./helpers.ts";

const FIXTURES = path.join(ROOT, "test", "fixtures");
const HEADER = "// Generated by duckwright from history.json. Review before committing:\n"
  + "// recorded code contains everything the agent typed, passwords included.\n"
  + "import { test, expect } from '@playwright/test';\n";
const GOTO = "await page.goto('https://example.com/form');";
const FILL = "await page.getByRole('textbox', { name: 'Name' }).fill('Linh');";
const CLICK = "await page.getByRole('button', { name: 'Submit' }).click();";
const EXPECT = "await expect(page.getByText('Hello, Linh!')).toHaveText(\"Hello, Linh!\");";

type Act = [cmd: string, args: string[], code: string | null];

function step(actions: Act[], results?: unknown): Record<string, unknown> {
  const acts = actions.map(([cmd, args, code]) => ({ cmd, args, code }));
  return { step: 0, evaluation_previous_goal: "", memory: "", next_goal: "", actions: acts, results: results ?? acts.map(() => "ok") };
}

function run(steps: Record<string, unknown>[], task = "greet", success = true): HistoryData {
  return { task, task_file: null, success, answer: "", steps: steps.length, cost_usd: 0, history: steps } as unknown as HistoryData;
}

function writeRun(tmp: string, data: unknown, name = "r1"): string {
  const runDir = path.join(tmp, "runs", name);
  fs.mkdirSync(runDir, { recursive: true });
  fs.writeFileSync(path.join(runDir, "history.json"), JSON.stringify(data));
  return runDir;
}

const exportError = (code: number, re?: RegExp) => (e: unknown) =>
  e instanceof ExportError && e.exitCode === code && (!re || re.test(e.message));

const GREET = run([
  step([["goto", ["https://example.com/form"], GOTO]]),
  step([["fill", ["e1", "Linh"], FILL], ["click", ["e2"], CLICK]]),
  step([["expect", ["text", "e3", "Hello, Linh!"], EXPECT], ["done", ["success", "Hello, Linh!"], null]], ["ok", "done"]),
]);

test("renders_exact_spec", () => {
  const { spec, warnings } = renderSpec(GREET);
  assert.equal(spec, HEADER + "\n" + 'test("greet", async ({ page }) => {\n'
    + `  ${GOTO}\n  ${FILL}\n  ${CLICK}\n  ${EXPECT}\n` + "});\n");
  assert.deepEqual(warnings, []);
});

test("skips_null_code_and_screenshot", () => {
  const { spec } = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["click", ["e9"], null]], ["error: nope"]),
    step([["screenshot", [], "await page.screenshot({ path: 'x.png' });"]]),
    step([["expect", ["visible", "e1"], EXPECT]]),
  ]));
  assert.ok(!spec.includes("screenshot"));
  assert.equal(spec.split("await ").length - 1, 2);
});

test("multiline_code_is_indented", () => {
  const { spec } = renderSpec(run([step([["click", ["e1"], "await a;\nawait b;"]]), step([["expect", [], EXPECT]])]));
  assert.ok(spec.includes("  await a;\n  await b;\n"));
});

test("title_is_json_escaped", () => {
  const task = 'say "hi"\\ */ \nnow';
  const { spec } = renderSpec({ ...GREET, task });
  const lines = spec.split("\n");
  assert.equal(lines.slice(0, 3).join("\n") + "\n", HEADER);
  assert.ok(lines.includes("test(" + JSON.stringify(task) + ", async ({ page }) => {"));
});

test("failed_run_is_refused", () => {
  assert.throws(() => renderSpec({ ...GREET, success: false }), exportError(1, /did not succeed/));
});

test("nothing_to_export_is_refused", () => {
  const data = run([step([["done", ["success", "x"], null]], ["done"])]);
  assert.throws(() => renderSpec(data), exportError(1, /nothing to export/));
  const runDir = writeRun(tmpDir(), data);
  assert.throws(() => exportRun(runDir), ExportError);
  assert.equal(fs.existsSync(path.join(runDir, SPEC_NAME)), false);
});

test("no_assertions_warns", () => {
  const { warnings } = renderSpec(run([step([["goto", ["u"], GOTO]])]));
  assert.ok(warnings.includes("no assertions recorded; add expect(...) lines by hand"));
});

const TAB_SIG = 'test("greet", async ({ page: firstPage }) => {\n  let page = firstPage;\n';

test("tab_new_with_url_emits_new_page_and_goto", () => {
  const { spec, warnings } = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["tab-new", ["https://x/\"y"], null]]),
    step([["expect", [], EXPECT]]),
  ]));
  assert.equal(spec, HEADER + "\n" + TAB_SIG + `  ${GOTO}\n  page = await page.context().newPage();\n`
    + '  await page.goto("https://x/\\"y");\n' + `  ${EXPECT}\n` + "});\n");
  assert.ok(!spec.includes("TODO"));
  assert.ok(!spec.includes("selectTab") && !spec.includes("closeTab"));
  assert.deepEqual(warnings, []);
});

test("tab_new_without_url_emits_only_new_page", () => {
  const { spec } = renderSpec(run([step([["goto", ["u"], GOTO]]), step([["tab-new", [], null]]), step([["tab-new", [""], null]])]));
  assert.equal((spec.match(/newPage\(\)/g) ?? []).length, 2);
  assert.equal(spec.split("goto").length, 2); // only the recorded goto
});

for (const arg of ["1", 1]) {
  test(`tab_select_accepts_${JSON.stringify(arg)}`, () => {
    const { spec } = renderSpec(run([step([["goto", ["u"], GOTO]]), step([["tab-select", [arg as string], null]])]));
    assert.ok(spec.includes("  page = await selectTab(page, 1);\n"));
    assert.ok(spec.includes(SELECT_TAB_HELPER));
    assert.ok(!spec.includes(CLOSE_TAB_HELPER));
    assert.ok(spec.includes(HEADER + "\n" + SELECT_TAB_HELPER + "\n" + TAB_SIG));
  });
}

test("tab_close_with_and_without_index", () => {
  const { spec } = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["tab-close", [], null]]),
    step([["tab-close", ["0"], null]]),
  ]));
  assert.ok(spec.includes("  page = await closeTab(page);\n  page = await closeTab(page, 0);\n"));
  assert.ok(spec.includes(CLOSE_TAB_HELPER));
  assert.ok(!spec.includes(SELECT_TAB_HELPER));
});

test("both_helpers_are_emitted_in_order_when_used", () => {
  const { spec } = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["tab-new", [], null]]),
    step([["tab-select", [0 as unknown as string], null]]),
    step([["tab-close", [], null]]),
  ]));
  assert.ok(spec.includes(HEADER + "\n" + SELECT_TAB_HELPER + "\n" + CLOSE_TAB_HELPER + "\n" + TAB_SIG));
});

test("tab_helpers_state_and_totp_order", () => {
  const totp = run([
    step([["twofa", ["totp"], "await page.getByLabel('Code').fill('[2FA CODE]');"]]),
    step([["tab-select", ["1"], null]]),
  ]);
  const { spec } = renderSpec({ ...totp, state: STATE_LOGIN });
  assert.ok(spec.includes(TOTP_HELPER + "\n" + SELECT_TAB_HELPER + "\n" + LOGIN_BLOCK + "\n" + TAB_SIG));
});

test("tab_helpers_and_state_without_totp", () => {
  const { spec } = renderSpec({ ...run([step([["goto", ["u"], GOTO]]), step([["tab-close", [], null]])]), state: STATE_LOGIN });
  assert.ok(spec.includes(HEADER + "\n" + CLOSE_TAB_HELPER + "\n" + LOGIN_BLOCK + "\n" + TAB_SIG));
});

test("failed_tab_command_adds_nothing", () => {
  const plain = renderSpec(run([step([["goto", ["u"], GOTO]]), step([["expect", [], EXPECT]])]));
  const withFailed = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["tab-new", ["x"], null], ["tab-select", ["x"], null]], ["error: boom", "error: no tab"]),
    step([["expect", [], EXPECT]]),
  ]));
  assert.deepEqual(withFailed, plain);
});

for (const [cmd, args] of [["tab-select", []], ["tab-select", ["x"]], ["tab-select", ["-1"]], ["tab-select", [1.5]], ["tab-close", ["abc"]]] as const) {
  test(`bad_tab_index ${cmd} ${JSON.stringify(args)}`, () => {
    const want = `${cmd} in step 2 has no valid tab index (expected a whole number, got ${JSON.stringify(args[0] ?? null)})`;
    assert.throws(
      () => renderSpec(run([step([["goto", ["u"], GOTO]]), step([[cmd, args as unknown as string[], null]])])),
      (e: unknown) => e instanceof ExportError && e.exitCode === 1 && e.message === want,
    );
  });
}

interface FakePage { name: string; context: () => { pages: () => FakePage[] }; bringToFront: () => Promise<void>; close: () => Promise<void> }

function fakeContext(names: string[]): { pages: FakePage[]; front: string[] } {
  const pages: FakePage[] = [];
  const front: string[] = [];
  const ctx = { pages: () => [...pages] };
  for (const name of names) {
    const page: FakePage = {
      name,
      context: () => ctx,
      bringToFront: async () => { front.push(name); },
      close: async () => { pages.splice(pages.indexOf(page), 1); },
    };
    pages.push(page);
  }
  return { pages, front };
}

const helpers = new Function(`${SELECT_TAB_HELPER}\n${CLOSE_TAB_HELPER}\nreturn { selectTab, closeTab };`)() as {
  selectTab: (current: FakePage, index: number) => Promise<FakePage>;
  closeTab: (current: FakePage, index?: number) => Promise<FakePage>;
};

test("select_tab_helper_brings_the_page_to_front", async () => {
  const { pages, front } = fakeContext(["a", "b", "c"]);
  assert.equal(await helpers.selectTab(pages[0], 2), pages[2]);
  assert.deepEqual(front, ["c"]);
  await assert.rejects(helpers.selectTab(pages[0], 5), /no tab 5/);
});

test("close_tab_helper_picks_the_current_tab", async () => {
  let f = fakeContext(["a", "b", "c"]);
  let [, mid, last] = f.pages;
  assert.equal(await helpers.closeTab(mid), last); // middle: the page now at the same index
  assert.deepEqual(f.front, ["c"]);
  f = fakeContext(["a", "b", "c"]);
  [, mid, last] = f.pages;
  assert.equal(await helpers.closeTab(last), mid); // last: the new last
  f = fakeContext(["a", "b", "c"]);
  const current = f.pages[2];
  assert.equal(await helpers.closeTab(current, 0), current); // another tab: current stays
  assert.deepEqual(f.pages.map((p) => p.name), ["b", "c"]);
  assert.deepEqual(f.front, []);
});

test("close_tab_helper_throws_on_the_last_tab_and_bad_index", async () => {
  const { pages } = fakeContext(["a"]);
  await assert.rejects(helpers.closeTab(pages[0]), /closed the last tab/);
  const two = fakeContext(["a", "b"]);
  await assert.rejects(helpers.closeTab(two.pages[0], 9), /no tab 9/);
});

test("load_history_accepts_dir_and_file", () => {
  const runDir = writeRun(tmpDir(), GREET);
  assert.deepEqual(loadHistory(runDir), { runDir, data: GREET });
  assert.deepEqual(loadHistory(path.join(runDir, "history.json")), { runDir, data: GREET });
});

const BAD: (string | null)[] = [
  null, // missing path
  "dir", // directory without history.json
  "not json",
  "[]",
  JSON.stringify({ task: "t", success: true }),
  JSON.stringify({ task: "t", success: true, history: {} }),
  JSON.stringify({ task: "t", success: "true", history: [] }),
  JSON.stringify({ task: "t", success: true, history: [{ actions: {} }] }),
  JSON.stringify({ task: "t", success: true, history: [[]] }),
  JSON.stringify({ task: "t", success: true, history: [{ actions: [{ cmd: ["x"], code: "await a;" }] }] }),
  JSON.stringify({ task: "t", success: true, history: [{ actions: [{ cmd: "click", code: 1 }] }] }),
  '{"task":"t","success":true,"history":' + "[".repeat(100_000),
  Buffer.from([0xff, 0xfe]).toString("latin1"),
];

for (const [i, content] of BAD.entries()) {
  test(`load_history_rejects_bad_input ${i}`, () => {
    const p = path.join(tmpDir(), "run");
    if (content !== null) fs.mkdirSync(p);
    if (content !== null && content !== "dir") {
      fs.writeFileSync(path.join(p, "history.json"), i === BAD.length - 1 ? Buffer.from([0xff, 0xfe]) : content);
    }
    assert.throws(() => loadHistory(p), exportError(2));
  });
}

test("load_history_error_messages", () => {
  const p = path.join(tmpDir(), "run");
  assert.throws(() => loadHistory(p), exportError(2, new RegExp(`^history not found: ${p}$`)));
  fs.mkdirSync(p);
  fs.writeFileSync(path.join(p, "history.json"), "not json");
  assert.throws(() => loadHistory(p), exportError(2, /^cannot read .*history\.json: /));
  fs.writeFileSync(path.join(p, "history.json"), "[]");
  assert.throws(() => loadHistory(p), exportError(2, /^not a duckwright history: .*history\.json: expected a JSON object$/));
});

test("export_run_default_and_custom_output", () => {
  const tmp = tmpDir();
  const runDir = writeRun(tmp, GREET);
  const { path: p, warnings } = exportRun(runDir);
  assert.equal(p, path.join(runDir, SPEC_NAME));
  assert.equal(fs.readFileSync(p, "utf8"), renderSpec(GREET).spec);
  assert.deepEqual(warnings, []);
  const out = path.join(tmp, "a", "b", "x.spec.ts");
  assert.equal(exportRun(runDir, out).path, out);
  assert.ok(fs.statSync(out).isFile());
  assert.equal(exportRun(runDir, out).path, out); // overwrite is fine
});

test("whitespace_only_code_is_not_code", () => {
  assert.throws(() => renderSpec(run([step([["click", ["e1"], "  \n "]])])), exportError(1, /nothing to export/));
});

for (const results of [undefined, "ok", ["ok"]]) {
  test(`missing_or_short_results_still_render ${JSON.stringify(results)}`, () => {
    const rec = step([["goto", ["u"], GOTO], ["tab-new", ["x"], null]]);
    if (results === undefined) delete rec.results;
    else rec.results = results;
    const { spec } = renderSpec(run([rec]));
    assert.ok(spec.includes(GOTO));
    assert.ok(!spec.includes("TODO")); // a tab command with no "ok" result adds nothing
    assert.ok(!spec.includes("newPage"));
  });
}

test("export_refuses_to_overwrite_history", () => {
  const runDir = writeRun(tmpDir(), GREET);
  assert.throws(() => exportRun(runDir, path.join(runDir, "history.json")), exportError(2));
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(runDir, "history.json"), "utf8")), GREET);
});

test("export refuses a symlink to the run's history", () => {
  const tmp = tmpDir();
  const runDir = writeRun(tmp, GREET);
  const link = path.join(tmp, "link.spec.ts");
  fs.symlinkSync(path.join(runDir, "history.json"), link);
  assert.throws(() => exportRun(runDir, link), exportError(2, /refusing to overwrite the run's history/));
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(runDir, "history.json"), "utf8")), GREET);
});

test("export_write_failure_is_exit_2", () => {
  const tmp = tmpDir();
  const runDir = writeRun(tmp, GREET);
  fs.writeFileSync(path.join(tmp, "file"), "");
  assert.throws(() => exportRun(runDir, path.join(tmp, "file", "x.spec.ts")), exportError(2, /^cannot write /));
});

test("non_ascii_task_round_trips", () => {
  const runDir = writeRun(tmpDir(), { ...GREET, task: "Chào Linh ✓" });
  const { path: p } = exportRun(runDir);
  assert.ok(fs.readFileSync(p, "utf8").includes('test("Chào Linh ✓"'));
});

for (const name of ["greet", "multiline", "tabs", "unicode"]) {
  test(`spec matches legacy output: ${name}`, () => {
    const dir = path.join(FIXTURES, "export", name);
    const { spec } = renderSpec(loadHistory(dir).data);
    assert.equal(spec, fs.readFileSync(path.join(dir, "expected.spec.ts"), "utf8"));
  });
}

test("spec_ignores_network_fields", () => {
  const dir = path.join(FIXTURES, "export", "greet");
  const data = JSON.parse(fs.readFileSync(path.join(dir, "history.json"), "utf8"));
  for (const s of data.history) {
    s.network = [{ id: "0001", method: "GET", url: "http://h/", status: 200, statusText: "OK", type: "fetch", durationMs: 1 }];
    s.network_errors = ["requests: x"];
  }
  const runDir = writeRun(tmpDir(), data);
  assert.equal(renderSpec(loadHistory(runDir).data).spec, fs.readFileSync(path.join(dir, "expected.spec.ts"), "utf8"));
});

const REQ = "const apiResponse1 = page.waitForResponse(...);";
const armOf = (n: number, method: string, p: string, status: number) =>
  `const apiResponse${n} = page.waitForResponse((r) => r.request().method() === "${method}" && new URL(r.url()).pathname === "${p}" && r.status() === ${status});`;

test("expect_request_arm_is_hoisted_to_the_previous_step", () => {
  const { spec, warnings } = renderSpec(run([
    step([["goto", ["https://example.com/form"], GOTO]]),
    step([["click", ["e2"], CLICK]]),
    step([["expect-request", ["POST", "/api/login", "201"], REQ], ["done", ["success", "x"], null]], ["ok", "done"]),
  ]));
  assert.equal(spec, HEADER + "\n" + 'test("greet", async ({ page }) => {\n'
    + `  ${GOTO}\n  ${armOf(1, "POST", "/api/login", 201)}\n  ${CLICK}\n  expect((await apiResponse1).status()).toBe(201);\n` + "});\n");
  assert.deepEqual(warnings, []);
});

test("two_expect_requests_get_distinct_names_and_order", () => {
  const { spec } = renderSpec(run([
    step([["click", ["e2"], CLICK]]),
    step([["expect-request", ["POST", "/a", "201"], REQ], ["expect-request", ["GET", "/b", "200"], REQ]]),
  ]));
  assert.equal(spec, HEADER + "\n" + 'test("greet", async ({ page }) => {\n'
    + `  ${armOf(1, "POST", "/a", 201)}\n  ${armOf(2, "GET", "/b", 200)}\n  ${CLICK}\n`
    + "  expect((await apiResponse1).status()).toBe(201);\n  expect((await apiResponse2).status()).toBe(200);\n" + "});\n");
});

test("expect_request_with_field_emits_body_lines", () => {
  const { spec } = renderSpec(run([
    step([["click", ["e2"], CLICK]]),
    step([["expect-request", ["GET", "/api/items", "200", "data.items.0.id", "42"], REQ]]),
  ]));
  assert.ok(spec.includes("  const apiBody1 = await (await apiResponse1).json();\n"));
  assert.ok(spec.includes('  expect(String(apiBody1?.data?.items?.[0]?.id)).toBe("42");\n'));
});

test("expect_request_in_first_step_or_with_bad_args_is_skipped_with_warning", () => {
  const first = renderSpec(run([
    step([["expect-request", ["GET", "/a", "200"], REQ], ["click", ["e2"], CLICK]]),
  ]));
  assert.ok(!first.spec.includes("waitForResponse"));
  assert.ok(first.warnings.includes("expect-request in step 1 has no earlier step to arm; skipped"));
  const bad = renderSpec(run([
    step([["click", ["e2"], CLICK]]),
    step([["expect-request", ["GET", "/a?x=1", "200"], REQ]]),
  ]));
  assert.ok(!bad.spec.includes("waitForResponse"));
  assert.ok(bad.warnings.includes("expect-request with invalid arguments skipped: error: expect-request url must not include a query or fragment"));
});

test("failed_expect_request_with_null_code_is_not_exported", () => {
  const { spec, warnings } = renderSpec(run([
    step([["click", ["e2"], CLICK]]),
    step([["expect-request", ["GET", "/a", "200"], null]], ["error: expect-request failed: no GET /a"]),
  ]));
  assert.ok(!spec.includes("waitForResponse"));
  assert.ok(warnings.includes(NO_ASSERTIONS));
});

const WITH_CALL = {
  ...GREET,
  history: [{ ...(GREET.history[0] as object), network: [
    { id: "0001", method: "GET", url: "http://a/api/x", status: 200, statusText: "OK", type: "fetch", durationMs: 1 },
  ] }],
};

test("export_run_api_writes_default_api_spec", () => {
  const runDir = writeRun(tmpDir(), WITH_CALL);
  const { path: p } = exportRun(runDir, null, true);
  assert.equal(p, path.join(runDir, "duckwright.api.spec.ts"));
  assert.match(fs.readFileSync(p, "utf8"), /async \(\{ request \}\)/);
  assert.equal(fs.existsSync(path.join(runDir, SPEC_NAME)), false);
});

test("export_run_api_refuses_overwriting_history", () => {
  const runDir = writeRun(tmpDir(), WITH_CALL);
  assert.throws(() => exportRun(runDir, path.join(runDir, "history.json"), true), exportError(2, /overwrite/));
});

test("export_run_api_without_calls_exits_1", () => {
  assert.throws(() => exportRun(writeRun(tmpDir(), GREET), null, true), exportError(1, /no API calls/));
});

const ORIGIN = "https://shop.example.com";
const reqStep = (args: string[], result: string, origin: string | null = ORIGIN) => ({
  ...step([["request", args, "request x"]], [result]),
  request_origins: [origin],
});

test("request_before_ui_is_exported_as_setup", () => {
  const { spec, warnings } = renderSpec(run([
    reqStep(["POST", "/api/items", '{"title":"x"}'], 'ok 201 {"id":7}'),
    step([["goto", ["https://example.com/"], GOTO]]),
    step([["expect", [], EXPECT]]),
  ]));
  assert.ok(spec.includes("  // setup: POST /api/items\n"));
  assert.ok(spec.includes('  const apiRequest1 = await page.request.fetch("https://shop.example.com/api/items", { method: "POST", maxRedirects: 0, data: {"title":"x"} });\n'));
  assert.ok(spec.includes("  expect(apiRequest1.status()).toBe(201);\n"));
  assert.ok(spec.indexOf("// setup:") < spec.indexOf("page.goto"));
  assert.ok(warnings.some((w) => /storageState/.test(w)));
});

test("expected_status_arg_wins_over_the_recorded_status", () => {
  const { spec } = renderSpec(run([
    reqStep(["POST", "/api/items", "{}", "202"], "ok 202"),
    step([["goto", ["u"], GOTO]]),
  ]));
  assert.ok(spec.includes("toBe(202)"));
});

test("request_after_a_ui_action_fails_the_export", () => {
  assert.throws(() => renderSpec(run([
    step([["click", ["e1"], null]]),
    reqStep(["POST", "/api/items", "{}"], "ok 201"),
  ])), exportError(1, /request in step 2 comes after a UI action in step 1/));
});

test("request_after_goto_is_exported_after_the_goto_line", () => {
  const { spec } = renderSpec(run([
    step([["goto", ["https://example.com/"], GOTO]]),
    reqStep(["POST", "/api/items", '{"title":"x"}'], "ok 201"),
    step([["expect", [], EXPECT]]),
  ]));
  assert.ok(spec.includes("// setup: POST /api/items"));
  assert.ok(spec.indexOf("page.goto") < spec.indexOf("// setup:"));
});

test("goto_then_click_then_request_still_fails", () => {
  assert.throws(() => renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["click", ["e1"], null]]),
    reqStep(["POST", "/api/items", "{}"], "ok 201"),
  ])), exportError(1, /request in step 3 comes after a UI action in step 2/));
});

test("request_after_tab_new_still_fails", () => {
  assert.throws(() => renderSpec(run([
    step([["tab-new", [], null]]),
    reqStep(["GET", "/api/items"], "ok 200"),
  ])), exportError(1, /request in step 2 comes after a UI action in step 1/));
});

test("request_in_the_same_step_after_an_ok_fill_fails", () => {
  const same = { ...step([["fill", ["e1", "x"], null], ["request", ["GET", "/api/items", "", "200"], "request x"]]), request_origins: [null, ORIGIN] };
  assert.throws(() => renderSpec(run([same])), exportError(1, /request in step 1 comes after a UI action in step 1/));
});

test("request_after_only_expect_or_screenshot_is_fine", () => {
  const { spec } = renderSpec(run([
    step([["expect", [], EXPECT], ["screenshot", [], null]]),
    reqStep(["GET", "/api/items"], "ok 200"),
    step([["goto", ["u"], GOTO]]),
  ]));
  assert.ok(spec.includes("// setup: GET /api/items"));
});

test("ui_action_that_errored_or_was_skipped_does_not_count", () => {
  const { spec } = renderSpec(run([
    step([["click", ["e1"], null]], ["error: no such element"]),
    reqStep(["GET", "/api/items"], "ok 200"),
    step([["goto", ["u"], GOTO]]),
  ]));
  assert.ok(spec.includes("// setup: GET /api/items"));
});

test("failed_request_is_skipped_with_a_warning", () => {
  const failed = { ...step([["request", ["POST", "/api/items", "{}"], null]], ["error: request POST /api/items returned 500 boom"]), request_origins: [null] };
  const { spec, warnings } = renderSpec(run([failed, step([["goto", ["u"], GOTO]])]));
  assert.ok(!spec.includes("setup:"));
  assert.ok(warnings.some((w) => /request in step 1 failed/.test(w)));
});

test("request_without_a_recorded_origin_is_skipped_with_a_warning", () => {
  const { spec, warnings } = renderSpec(run([
    reqStep(["GET", "/api/items"], "ok 200", null),
    step([["goto", ["u"], GOTO]]),
  ]));
  assert.ok(!spec.includes("setup:"));
  assert.ok(warnings.some((w) => /no recorded origin/.test(w)));
});

test("request_with_secret_body_warns", () => {
  const { warnings } = renderSpec(run([
    reqStep(["POST", "/api/login", '{"user":"a","password":"hunter2"}'], "ok 200"),
    step([["goto", ["u"], GOTO]]),
  ]));
  assert.ok(warnings.some((w) => /request in step 1 has a body; check it for secrets/.test(w)));
});

test("request_with_invalid_args_is_skipped_with_a_warning", () => {
  const { spec, warnings } = renderSpec(run([
    reqStep(["GET", "/a?x=1"], "ok 200"),
    step([["goto", ["u"], GOTO]]),
  ]));
  assert.ok(!spec.includes("setup:"));
  assert.ok(warnings.some((w) => /request with invalid arguments skipped/.test(w)));
});

test("request_only_run_has_code_but_no_assertions_warning", () => {
  const { warnings } = renderSpec(run([reqStep(["GET", "/api/items"], "ok 200")]));
  assert.ok(warnings.includes(NO_ASSERTIONS));
});

const MASKED_FILL = "await page.getByLabel('Code').fill('[2FA CODE]');";

test("twofa_totp_exports_a_helper_call_not_a_code", () => {
  const { spec, warnings } = renderSpec(run([
    step([["goto", ["https://example.com/login"], GOTO]]),
    step([["twofa", ["totp", "e5"], MASKED_FILL]]),
    step([["expect", ["url", "https://example.com/home"], EXPECT]]),
  ]));
  assert.ok(spec.includes(TOTP_IMPORT));
  assert.ok(spec.includes(TOTP_HELPER));
  assert.ok(spec.includes("  await page.getByLabel('Code').fill(totp()); // 2FA\n"));
  assert.ok(!spec.includes("[2FA CODE]"));
  assert.ok(!spec.includes("cannot run unattended"));
  assert.deepEqual(warnings, []);
});

test("twofa_totp_keeps_the_submit_lines_after_the_fill", () => {
  const { spec } = renderSpec(run([
    step([["goto", ["https://example.com/login"], GOTO]]),
    step([["twofa", ["totp", "e5"], `${MASKED_FILL}\nawait page.getByLabel('Code').press('Enter');`]]),
  ]));
  assert.ok(spec.includes("  await page.getByLabel('Code').fill(totp()); // 2FA\n  await page.getByLabel('Code').press('Enter');\n"));
});

test("twofa_human_kinds_export_as_manual_steps_with_a_header_note_and_warnings", () => {
  const { spec, warnings } = renderSpec(run([
    step([["goto", ["https://example.com/login"], GOTO]]),
    step([["twofa", ["sms", "e5"], MASKED_FILL]]),
    step([["twofa", ["email", "e6"], MASKED_FILL]]),
    step([["twofa", ["passkey"], null]]),
    step([["expect", ["url", "https://example.com/home"], EXPECT]]),
  ]));
  assert.ok(spec.includes("  // MANUAL: enter the sms code here\n  await page.pause();\n"));
  assert.ok(spec.includes("  // MANUAL: enter the email code here\n  await page.pause();\n"));
  assert.ok(spec.includes("  // MANUAL: approve the passkey prompt\n  await page.pause();\n"));
  assert.ok(spec.includes("cannot run unattended"));
  assert.ok(!spec.includes("[2FA CODE]"));
  assert.ok(!spec.includes("totp()"));
  assert.deepEqual(warnings, [
    "twofa sms in step 2 is a manual step; the test cannot run unattended",
    "twofa email in step 3 is a manual step; the test cannot run unattended",
    "twofa passkey in step 4 is a manual step; the test cannot run unattended",
  ]);
});

test("twofa_without_a_recorded_code_fails_the_export_except_passkey", () => {
  assert.throws(() => renderSpec(run([step([["twofa", ["totp", "e5"], null]])])),
    exportError(1, /twofa in step 1 has no recorded code/));
  assert.throws(() => renderSpec(run([step([["twofa", ["sms", "e5"], null]])])),
    exportError(1, /twofa in step 1 has no recorded code/));
});

test("a_totp_step_whose_code_has_no_mask_fails_the_export", () => {
  assert.throws(() => renderSpec(run([step([["twofa", ["totp", "e5"], "await page.getByLabel('Code').fill('123456');"]])])),
    exportError(1, /twofa in step 1 has no recorded code/));
});

test("a_failed_twofa_is_skipped_with_a_warning", () => {
  const { warnings } = renderSpec(run([
    step([["goto", ["https://example.com/login"], GOTO]]),
    step([["twofa", ["sms", "e5"], null]], ["error: timed out waiting for the 2FA code"]),
    step([["expect", ["url", "https://example.com/home"], EXPECT]]),
  ]));
  assert.deepEqual(warnings, ["twofa in step 2 failed and was skipped"]);
});

test("a_request_after_twofa_is_refused_like_one_after_any_ui_action", () => {
  assert.throws(() => renderSpec(run([
    step([["goto", ["https://example.com/login"], GOTO]]),
    step([["twofa", ["totp", "e5"], MASKED_FILL]]),
    { ...step([["request", ["POST", "/api/x"], "marker"]], ["ok 201"]), request_origins: ["https://example.com"] },
  ])), exportError(1, /request in step 3 comes after a UI action in step 2/));
});

test("the_totp_helper_matches_rfc_6238", () => {
  const body = `${TOTP_HELPER}\nreturn totp();`;
  const at = (seconds: number, secret = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"): string =>
    new Function("createHmac", "process", "Date", body)(
      createHmac, { env: { DUCKWRIGHT_TOTP_SECRET: secret } }, { now: () => seconds * 1000 });
  assert.equal(at(59), "287082");
  assert.equal(at(1111111109), "081804");
  assert.equal(at(20000000000), "353130");
  assert.equal(at(59, "otpauth://totp/x?secret=GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ&issuer=x"), "287082");
});

test("the_totp_helper_demands_the_env_secret", () => {
  assert.throws(() => new Function("createHmac", "process", "Date", `${TOTP_HELPER}\nreturn totp();`)(
    createHmac, { env: {} }, Date), /set DUCKWRIGHT_TOTP_SECRET to run this test/);
});

test("export accepts history with jev fields", () => {
  const jevStep = {
    ...step([["goto", ["https://example.com/form"], GOTO], ["click", ["e1"], CLICK]]),
    cost_usd: 0.0000012, source: "jev",
    jev: { action: "click", action_confidence: 0.93, target: "e1", target_confidence: 0.88, routed: "accepted" },
  };
  const plain = run([step([["goto", ["https://example.com/form"], GOTO], ["click", ["e1"], CLICK]])]);
  const withJev = { ...run([jevStep]), jev_steps: 1, claude_steps: 0 } as HistoryData;
  assert.equal(renderSpec(withJev).spec, renderSpec(plain).spec);
});

const STATE_LOGIN = { path: ".duckwright/auth/staging.json", source: "login" as const };
const LOGIN_BLOCK = "// The run started from the storage state in .duckwright/auth/staging.json (auto-login).\n"
  + "// Set DUCKWRIGHT_STORAGE_STATE to use another file; in CI, supply one.\n"
  + 'test.use({ storageState: process.env.DUCKWRIGHT_STORAGE_STATE || ".duckwright/auth/staging.json" });\n';

test("state_login_renders_test_use_block", () => {
  const { spec } = renderSpec({ ...GREET, state: STATE_LOGIN });
  assert.equal(stateBlock(STATE_LOGIN), LOGIN_BLOCK);
  assert.equal(spec, HEADER + "\n" + LOGIN_BLOCK + "\n" + 'test("greet", async ({ page }) => {\n'
    + `  ${GOTO}\n  ${FILL}\n  ${CLICK}\n  ${EXPECT}\n` + "});\n");
});

test("state_file_says_state_flag", () => {
  const { spec } = renderSpec({ ...GREET, state: { path: "a.json", source: "file" } });
  assert.ok(spec.includes("// The run started from the storage state in a.json (--state).\n"));
  assert.ok(spec.includes('test.use({ storageState: process.env.DUCKWRIGHT_STORAGE_STATE || "a.json" });\n'));
});

test("state_block_goes_after_totp_helper", () => {
  const totp = run([step([["twofa", ["totp"], "await page.getByLabel('Code').fill('[2FA CODE]');"]]), step([["goto", ["u"], GOTO]])]);
  const { spec } = renderSpec({ ...totp, state: STATE_LOGIN });
  assert.ok(spec.includes(TOTP_HELPER + "\n" + LOGIN_BLOCK + "\ntest("));
});

test("state_path_with_newline_is_left_out_of_the_comment", () => {
  const block = stateBlock({ path: "a\nb.json", source: "file" });
  assert.equal(block.split("\n")[0], "// The run started from a storage state (--state).");
  assert.ok(block.includes('storageState: process.env.DUCKWRIGHT_STORAGE_STATE || "a\\nb.json"'));
  assert.equal(block.split("\n").length, 4);
});

test("state_replaces_the_cookies_note", () => {
  const steps = [reqStep(["POST", "/api/items", "{}"], "ok 201"), step([["goto", ["u"], GOTO]])];
  assert.ok(renderSpec(run(steps)).warnings.some((w) => /storageState/.test(w)));
  assert.ok(!renderSpec({ ...run(steps), state: STATE_LOGIN }).warnings.some((w) => /storageState/.test(w)));
});

for (const [i, state] of ["x", { path: 1 }, null, [], {}].entries()) {
  test(`load_history_rejects_bad_state ${i}`, () => {
    const runDir = writeRun(tmpDir(), { ...GREET, state });
    assert.throws(() => loadHistory(runDir), exportError(2, /^not a duckwright history: .*history\.json: 'state' must be an object with a string 'path'$/));
  });
}

test("load_history_accepts_state", () => {
  const runDir = writeRun(tmpDir(), { ...GREET, state: STATE_LOGIN });
  assert.deepEqual(loadHistory(runDir).data.state, STATE_LOGIN);
});
