import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";

import { ExportError, SPEC_NAME, exportRun, loadHistory, renderSpec } from "../src/export.ts";
import type { HistoryData } from "../src/export.ts";
import { ROOT, tmpDir } from "./helpers.ts";

const FIXTURES = path.join(ROOT, "test", "fixtures");
const HEADER = "// Generated by duckwright from history.json. Review before committing:\n"
  + "// recorded code contains everything the agent typed, passwords included.\n"
  + "import { test, expect } from '@playwright/test';\n";
const GOTO = "await page.goto('https://example.com/form');";
const FILL = "await page.getByRole('textbox', { name: 'Name' }).fill('Linh');";
const CLICK = "await page.getByRole('button', { name: 'Submit' }).click();";
const EXPECT = "await expect(page.getByText('Hello, Linh!')).toHaveText(\"Hello, Linh!\");";
const TAB_TODO = "  // TODO(duckwright): tab-new needs a hand edit; this test assumes a single page\n";

type Act = [cmd: string, args: string[], code: string | null];

function step(actions: Act[], results?: unknown): Record<string, unknown> {
  const acts = actions.map(([cmd, args, code]) => ({ cmd, args, code }));
  return { step: 0, evaluation_previous_goal: "", memory: "", next_goal: "", actions: acts, results: results ?? acts.map(() => "ok") };
}

function run(steps: Record<string, unknown>[], task = "greet", success = true): HistoryData {
  return { task, task_file: null, success, answer: "", steps: steps.length, cost_usd: 0, history: steps } as unknown as HistoryData;
}

function writeRun(tmp: string, data: unknown, name = "r1"): string {
  const runDir = path.join(tmp, "runs", name);
  fs.mkdirSync(runDir, { recursive: true });
  fs.writeFileSync(path.join(runDir, "history.json"), JSON.stringify(data));
  return runDir;
}

const exportError = (code: number, re?: RegExp) => (e: unknown) =>
  e instanceof ExportError && e.exitCode === code && (!re || re.test(e.message));

const GREET = run([
  step([["goto", ["https://example.com/form"], GOTO]]),
  step([["fill", ["e1", "Linh"], FILL], ["click", ["e2"], CLICK]]),
  step([["expect", ["text", "e3", "Hello, Linh!"], EXPECT], ["done", ["success", "Hello, Linh!"], null]], ["ok", "done"]),
]);

test("renders_exact_spec", () => {
  const { spec, warnings } = renderSpec(GREET);
  assert.equal(spec, HEADER + "\n" + 'test("greet", async ({ page }) => {\n'
    + `  ${GOTO}\n  ${FILL}\n  ${CLICK}\n  ${EXPECT}\n` + "});\n");
  assert.deepEqual(warnings, []);
});

test("skips_null_code_and_screenshot", () => {
  const { spec } = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["click", ["e9"], null]], ["error: nope"]),
    step([["screenshot", [], "await page.screenshot({ path: 'x.png' });"]]),
    step([["expect", ["visible", "e1"], EXPECT]]),
  ]));
  assert.ok(!spec.includes("screenshot"));
  assert.equal(spec.split("await ").length - 1, 2);
});

test("multiline_code_is_indented", () => {
  const { spec } = renderSpec(run([step([["click", ["e1"], "await a;\nawait b;"]]), step([["expect", [], EXPECT]])]));
  assert.ok(spec.includes("  await a;\n  await b;\n"));
});

test("title_is_json_escaped", () => {
  const task = 'say "hi"\\ */ \nnow';
  const { spec } = renderSpec({ ...GREET, task });
  const lines = spec.split("\n");
  assert.equal(lines.slice(0, 3).join("\n") + "\n", HEADER);
  assert.ok(lines.includes("test(" + JSON.stringify(task) + ", async ({ page }) => {"));
});

test("failed_run_is_refused", () => {
  assert.throws(() => renderSpec({ ...GREET, success: false }), exportError(1, /did not succeed/));
});

test("nothing_to_export_is_refused", () => {
  const data = run([step([["done", ["success", "x"], null]], ["done"])]);
  assert.throws(() => renderSpec(data), exportError(1, /nothing to export/));
  const runDir = writeRun(tmpDir(), data);
  assert.throws(() => exportRun(runDir), ExportError);
  assert.equal(fs.existsSync(path.join(runDir, SPEC_NAME)), false);
});

test("no_assertions_warns", () => {
  const { warnings } = renderSpec(run([step([["goto", ["u"], GOTO]])]));
  assert.ok(warnings.includes("no assertions recorded; add expect(...) lines by hand"));
});

test("tab_command_marks_todo_without_args", () => {
  const { spec, warnings } = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["tab-new", ["https://x\nawait evil();"], null]]),
    step([["tab-new", ["y"], null]]),
    step([["expect", [], EXPECT]]),
  ]));
  assert.ok(spec.includes(TAB_TODO));
  assert.ok(!spec.includes("evil"));
  assert.deepEqual(warnings, ["run used tab-new; edit the test by hand, it assumes a single page"]);
});

test("failed_tab_command_adds_nothing", () => {
  const { spec, warnings } = renderSpec(run([
    step([["goto", ["u"], GOTO]]),
    step([["tab-new", ["x"], null]], ["error: boom"]),
    step([["expect", [], EXPECT]]),
  ]));
  assert.ok(!spec.includes("TODO"));
  assert.deepEqual(warnings, []);
});

test("load_history_accepts_dir_and_file", () => {
  const runDir = writeRun(tmpDir(), GREET);
  assert.deepEqual(loadHistory(runDir), { runDir, data: GREET });
  assert.deepEqual(loadHistory(path.join(runDir, "history.json")), { runDir, data: GREET });
});

const BAD: (string | null)[] = [
  null, // missing path
  "dir", // directory without history.json
  "not json",
  "[]",
  JSON.stringify({ task: "t", success: true }),
  JSON.stringify({ task: "t", success: true, history: {} }),
  JSON.stringify({ task: "t", success: "true", history: [] }),
  JSON.stringify({ task: "t", success: true, history: [{ actions: {} }] }),
  JSON.stringify({ task: "t", success: true, history: [[]] }),
  JSON.stringify({ task: "t", success: true, history: [{ actions: [{ cmd: ["x"], code: "await a;" }] }] }),
  JSON.stringify({ task: "t", success: true, history: [{ actions: [{ cmd: "click", code: 1 }] }] }),
  '{"task":"t","success":true,"history":' + "[".repeat(100_000),
  Buffer.from([0xff, 0xfe]).toString("latin1"),
];

for (const [i, content] of BAD.entries()) {
  test(`load_history_rejects_bad_input ${i}`, () => {
    const p = path.join(tmpDir(), "run");
    if (content !== null) fs.mkdirSync(p);
    if (content !== null && content !== "dir") {
      fs.writeFileSync(path.join(p, "history.json"), i === BAD.length - 1 ? Buffer.from([0xff, 0xfe]) : content);
    }
    assert.throws(() => loadHistory(p), exportError(2));
  });
}

test("load_history_error_messages", () => {
  const p = path.join(tmpDir(), "run");
  assert.throws(() => loadHistory(p), exportError(2, new RegExp(`^history not found: ${p}$`)));
  fs.mkdirSync(p);
  fs.writeFileSync(path.join(p, "history.json"), "not json");
  assert.throws(() => loadHistory(p), exportError(2, /^cannot read .*history\.json: /));
  fs.writeFileSync(path.join(p, "history.json"), "[]");
  assert.throws(() => loadHistory(p), exportError(2, /^not a duckwright history: .*history\.json: expected a JSON object$/));
});

test("export_run_default_and_custom_output", () => {
  const tmp = tmpDir();
  const runDir = writeRun(tmp, GREET);
  const { path: p, warnings } = exportRun(runDir);
  assert.equal(p, path.join(runDir, SPEC_NAME));
  assert.equal(fs.readFileSync(p, "utf8"), renderSpec(GREET).spec);
  assert.deepEqual(warnings, []);
  const out = path.join(tmp, "a", "b", "x.spec.ts");
  assert.equal(exportRun(runDir, out).path, out);
  assert.ok(fs.statSync(out).isFile());
  assert.equal(exportRun(runDir, out).path, out); // overwrite is fine
});

test("whitespace_only_code_is_not_code", () => {
  assert.throws(() => renderSpec(run([step([["click", ["e1"], "  \n "]])])), exportError(1, /nothing to export/));
});

for (const results of [undefined, "ok", ["ok"]]) {
  test(`missing_or_short_results_still_render ${JSON.stringify(results)}`, () => {
    const rec = step([["goto", ["u"], GOTO], ["tab-new", ["x"], null]]);
    if (results === undefined) delete rec.results;
    else rec.results = results;
    const { spec } = renderSpec(run([rec]));
    assert.ok(spec.includes(GOTO));
    assert.ok(!spec.includes("TODO")); // a tab command with no "ok" result is not marked
  });
}

test("export_refuses_to_overwrite_history", () => {
  const runDir = writeRun(tmpDir(), GREET);
  assert.throws(() => exportRun(runDir, path.join(runDir, "history.json")), exportError(2));
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(runDir, "history.json"), "utf8")), GREET);
});

test("export refuses a symlink to the run's history", () => {
  const tmp = tmpDir();
  const runDir = writeRun(tmp, GREET);
  const link = path.join(tmp, "link.spec.ts");
  fs.symlinkSync(path.join(runDir, "history.json"), link);
  assert.throws(() => exportRun(runDir, link), exportError(2, /refusing to overwrite the run's history/));
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(runDir, "history.json"), "utf8")), GREET);
});

test("export_write_failure_is_exit_2", () => {
  const tmp = tmpDir();
  const runDir = writeRun(tmp, GREET);
  fs.writeFileSync(path.join(tmp, "file"), "");
  assert.throws(() => exportRun(runDir, path.join(tmp, "file", "x.spec.ts")), exportError(2, /^cannot write /));
});

test("non_ascii_task_round_trips", () => {
  const runDir = writeRun(tmpDir(), { ...GREET, task: "Chào Linh ✓" });
  const { path: p } = exportRun(runDir);
  assert.ok(fs.readFileSync(p, "utf8").includes('test("Chào Linh ✓"'));
});

for (const name of ["greet", "multiline", "tabs", "unicode"]) {
  test(`spec matches legacy output: ${name}`, () => {
    const dir = path.join(FIXTURES, "export", name);
    const { spec } = renderSpec(loadHistory(dir).data);
    assert.equal(spec, fs.readFileSync(path.join(dir, "expected.spec.ts"), "utf8"));
  });
}
