import json

import pytest

from duckwright.export import SPEC_NAME, ExportError, export_run, load_history, render_spec

HEADER = (
    "// Generated by duckwright from history.json. Review before committing:\n"
    "// recorded code contains everything the agent typed, passwords included.\n"
    "import { test, expect } from '@playwright/test';\n"
)
GOTO = "await page.goto('https://example.com/form');"
FILL = "await page.getByRole('textbox', { name: 'Name' }).fill('Linh');"
CLICK = "await page.getByRole('button', { name: 'Submit' }).click();"
EXPECT = "await expect(page.getByText('Hello, Linh!')).toHaveText(\"Hello, Linh!\");"
TAB_TODO = "  // TODO(duckwright): tab-new needs a hand edit; this test assumes a single page\n"


def step(*actions, results=None):  # actions: (cmd, args, code)
    acts = [{"cmd": c, "args": a, "code": k} for c, a, k in actions]
    return {"step": 0, "evaluation_previous_goal": "", "memory": "", "next_goal": "",
            "actions": acts, "results": results or ["ok"] * len(acts)}


def run(*steps, task="greet", success=True):
    return {"task": task, "success": success, "answer": "", "steps": len(steps),
            "cost_usd": 0.0, "history": list(steps)}


def write_run(tmp_path, data, name="r1"):
    run_dir = tmp_path / "runs" / name
    run_dir.mkdir(parents=True)
    (run_dir / "history.json").write_text(json.dumps(data))
    return run_dir


GREET = run(
    step(("goto", ["https://example.com/form"], GOTO)),
    step(("fill", ["e1", "Linh"], FILL), ("click", ["e2"], CLICK)),
    step(("expect", ["text", "e3", "Hello, Linh!"], EXPECT),
         ("done", ["success", "Hello, Linh!"], None),
         results=["ok", "done"]),
)


def test_renders_exact_spec():
    spec, warnings = render_spec(GREET)
    assert spec == (
        HEADER
        + "\n"
        + 'test("greet", async ({ page }) => {\n'
        + f"  {GOTO}\n  {FILL}\n  {CLICK}\n  {EXPECT}\n"
        + "});\n"
    )
    assert warnings == []


def test_skips_null_code_and_screenshot():
    data = run(
        step(("goto", ["u"], GOTO)),
        step(("click", ["e9"], None), results=["error: nope"]),
        step(("screenshot", [], "await page.screenshot({ path: 'x.png' });")),
        step(("expect", ["visible", "e1"], EXPECT)),
    )
    spec, _ = render_spec(data)
    assert "screenshot" not in spec
    assert spec.count("await ") == 2


def test_multiline_code_is_indented():
    data = run(step(("click", ["e1"], "await a;\nawait b;")), step(("expect", [], EXPECT)))
    spec, _ = render_spec(data)
    assert "  await a;\n  await b;\n" in spec


def test_title_is_json_escaped():
    task = 'say "hi"\\ */ \nnow'
    spec, _ = render_spec({**GREET, "task": task})
    lines = spec.split("\n")
    assert "\n".join(lines[:3]) + "\n" == HEADER
    title = "test(" + json.dumps(task, ensure_ascii=False) + ", async ({ page }) => {"
    assert title in lines


def test_failed_run_is_refused():
    with pytest.raises(ExportError) as e:
        render_spec({**GREET, "success": False})
    assert e.value.exit_code == 1
    assert "did not succeed" in str(e.value)


def test_nothing_to_export_is_refused(tmp_path):
    data = run(step(("done", ["success", "x"], None), results=["done"]))
    with pytest.raises(ExportError) as e:
        render_spec(data)
    assert e.value.exit_code == 1
    assert "nothing to export" in str(e.value)
    run_dir = write_run(tmp_path, data)
    with pytest.raises(ExportError):
        export_run(run_dir)
    assert not (run_dir / SPEC_NAME).exists()


def test_no_assertions_warns():
    _, warnings = render_spec(run(step(("goto", ["u"], GOTO))))
    assert "no assertions recorded; add expect(...) lines by hand" in warnings


def test_tab_command_marks_todo_without_args():
    data = run(
        step(("goto", ["u"], GOTO)),
        step(("tab-new", ["https://x\nawait evil();"], None)),
        step(("tab-new", ["y"], None)),
        step(("expect", [], EXPECT)),
    )
    spec, warnings = render_spec(data)
    assert TAB_TODO in spec
    assert "evil" not in spec
    assert warnings == ["run used tab-new; edit the test by hand, it assumes a single page"]


def test_failed_tab_command_adds_nothing():
    data = run(
        step(("goto", ["u"], GOTO)),
        step(("tab-new", ["x"], None), results=["error: boom"]),
        step(("expect", [], EXPECT)),
    )
    spec, warnings = render_spec(data)
    assert "TODO" not in spec
    assert warnings == []


def test_load_history_accepts_dir_and_file(tmp_path):
    run_dir = write_run(tmp_path, GREET)
    assert load_history(run_dir) == (run_dir, GREET)
    assert load_history(run_dir / "history.json") == (run_dir, GREET)


@pytest.mark.parametrize(
    "content",
    [
        None,  # missing path
        "dir",  # directory without history.json
        "not json",
        "[]",
        json.dumps({"task": "t", "success": True}),
        json.dumps({"task": "t", "success": True, "history": {}}),
        json.dumps({"task": "t", "success": "true", "history": []}),
        json.dumps({"task": "t", "success": True, "history": [{"actions": {}}]}),
        json.dumps({"task": "t", "success": True, "history": [[]]}),
        json.dumps({"task": "t", "success": True,
                    "history": [{"actions": [{"cmd": ["x"], "code": "await a;"}]}]}),
        json.dumps({"task": "t", "success": True,
                    "history": [{"actions": [{"cmd": "click", "code": 1}]}]}),
        '{"task":"t","success":true,"history":' + "[" * 100_000,
    ],
)
def test_load_history_rejects_bad_input(tmp_path, content):
    path = tmp_path / "run"
    if content == "dir":
        path.mkdir()
    elif content is not None:
        path.mkdir()
        (path / "history.json").write_text(content)
    with pytest.raises(ExportError) as e:
        load_history(path)
    assert e.value.exit_code == 2


def test_export_run_default_and_custom_output(tmp_path):
    run_dir = write_run(tmp_path, GREET)
    path, warnings = export_run(run_dir)
    assert path == run_dir / SPEC_NAME
    assert path.read_text() == render_spec(GREET)[0]
    assert warnings == []
    out = tmp_path / "a" / "b" / "x.spec.ts"
    assert export_run(run_dir, out)[0] == out
    assert out.is_file()
    assert export_run(run_dir, out)[0] == out  # overwrite is fine


def test_whitespace_only_code_is_not_code():
    with pytest.raises(ExportError, match="nothing to export"):
        render_spec(run(step(("click", ["e1"], "  \n "))))


@pytest.mark.parametrize("results", [None, "ok", ["ok"]])
def test_missing_or_short_results_still_render(results):
    rec = step(("goto", ["u"], GOTO), ("tab-new", ["x"], None))
    rec["results"] = results
    if results is None:
        del rec["results"]
    spec, _ = render_spec(run(rec))
    assert GOTO in spec
    assert "TODO" not in spec  # a tab command with no "ok" result is not marked


def test_export_refuses_to_overwrite_history(tmp_path):
    run_dir = write_run(tmp_path, GREET)
    with pytest.raises(ExportError) as e:
        export_run(run_dir, run_dir / "history.json")
    assert e.value.exit_code == 2
    assert json.loads((run_dir / "history.json").read_text()) == GREET


def test_non_ascii_task_round_trips(tmp_path):
    run_dir = write_run(tmp_path, {**GREET, "task": "Chào Linh ✓"})
    path, _ = export_run(run_dir)
    assert 'test("Chào Linh ✓"' in path.read_text(encoding="utf-8")
