// Generated by duckwright from history.json. Review before committing:
// recorded code contains everything the agent typed, passwords included.
import { test, expect } from '@playwright/test';

test("Go to https://pokedex.org/ and wait until the list of Pokémon is shown.\nRight after that step, use expect-request to assert that the page loaded its data through the\nnetwork calls listed for that step. Do this before any other action, since expect-request only\nlooks at the previous step's calls.\nSearch for \"Charizard\" and open its page.\nReport its Pokédex number and which Pokémon it evolves from, and at what level.", async ({ page }) => {
  const apiResponse1 = page.waitForResponse((r) => r.request().method() === "GET" && new URL(r.url()).pathname === "/assets/skim-monsters-1.txt" && r.status() === 200);
  const apiResponse2 = page.waitForResponse((r) => r.request().method() === "GET" && new URL(r.url()).pathname === "/assets/evolutions.txt" && r.status() === 200);
  await page.goto('https://pokedex.org/');
  expect((await apiResponse1).status()).toBe(200);
  expect((await apiResponse2).status()).toBe(200);
  await page.getByRole('searchbox', { name: 'Search for Pokémon' }).fill('Charizard');
  await page.getByRole('listitem').filter({ hasText: 'Charizard' }).click();
});
