// Generated by duckwright from history.json. Review before committing:
// recorded code contains everything the agent typed, passwords included.
import { test, expect } from '@playwright/test';

test("Chào Linh ✓ say \"hi\"\\ */ \nnow", async ({ page }) => {
  await page.goto('https://example.com/form');
  await page.getByRole('textbox').fill('Đăng nhập ✓');
  await expect(page.getByText('Hello, Linh!')).toHaveText("Hello, Linh!");
});
