// Generated by duckwright from history.json. Review before committing:
// recorded code contains everything the agent typed, passwords included.
import { test, expect } from '@playwright/test';

test("tabs", async ({ page: firstPage }) => {
  let page = firstPage;
  await page.goto('https://example.com/form');
  page = await page.context().newPage();
  await page.goto("https://x\nawait evil();");
  await page.getByRole('button', { name: 'Submit' }).click();
});
