// Generated by duckwright from history.json. Review before committing:
// recorded code contains everything the agent typed, passwords included.
import { test, expect } from '@playwright/test';

test("tabs", async ({ page }) => {
  await page.goto('https://example.com/form');
  // TODO(duckwright): tab-new needs a hand edit; this test assumes a single page
  await page.getByRole('button', { name: 'Submit' }).click();
});
