import fs from "node:fs";
import path from "node:path";

import type { JevRecord } from "./brain.ts";
import { checkRequestArgs, renderRequestExpect } from "./expectRequest.ts";
import type { NetworkEntry } from "./network.ts";
import { renderApiSpec } from "./exportApi.ts";
import { resolvePath } from "./paths.ts";
import { redactBody } from "./redact.ts";
import { checkRequestCallArgs, renderRequestSetup } from "./request.ts";
import { CODE_MASK } from "./scrub.ts";
import { splitLines } from "./text.ts";

export const SPEC_NAME = "duckwright.spec.ts";
export const API_SPEC_NAME = "duckwright.api.spec.ts";
export const HEADER = "// Generated by duckwright from history.json. Review before committing:\n"
  + "// recorded code contains everything the agent typed, passwords included.\n"
  + "import { test, expect } from '@playwright/test';\n";
export const TAB_COMMANDS: ReadonlySet<string> = new Set(["tab-new", "tab-select", "tab-close"]);
const UI_COMMANDS: ReadonlySet<string> = new Set([
  "click", "fill", "type", "press", "select", "check", "uncheck", "dblclick", "hover", "drag", "go-back", ...TAB_COMMANDS,
]);
const COOKIES_NOTE = "request replays use the test's own browser context; add test.use({ storageState: 'auth.json' }) if the site needs the run's cookies";
export const NO_ASSERTIONS = "no assertions recorded; add expect(...) lines by hand";
export const TOTP_IMPORT = "import { createHmac } from 'node:crypto';\n";
// Plain JavaScript that is also valid TypeScript (no annotations), so the tests can run it as is.
export const TOTP_HELPER = `function totp() {
  let secret = process.env.DUCKWRIGHT_TOTP_SECRET;
  if (!secret) throw new Error('set DUCKWRIGHT_TOTP_SECRET to run this test');
  if (/^otpauth:/i.test(secret)) secret = new URL(secret).searchParams.get('secret') || '';
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  const bytes = [];
  let bits = 0;
  let acc = 0;
  for (const ch of secret.replace(/[\\s=-]/g, '').toUpperCase()) {
    acc = (acc << 5) | alphabet.indexOf(ch);
    bits += 5;
    if (bits >= 8) {
      bytes.push((acc >>> (bits - 8)) & 255);
      bits -= 8;
      acc &= (1 << bits) - 1;
    }
  }
  const counter = Buffer.alloc(8);
  counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000)));
  const mac = createHmac('sha1', Buffer.from(bytes)).update(counter).digest();
  const offset = mac[mac.length - 1] & 15;
  const value = ((mac[offset] & 127) << 24) | (mac[offset + 1] << 16) | (mac[offset + 2] << 8) | mac[offset + 3];
  return String(value % 1000000).padStart(6, '0');
}
`;
const MANUAL_NOTE = "// NOTE: this test has manual 2FA steps (marked MANUAL) and cannot run unattended.\n";
const MASKED_CODE = new RegExp(`(['"\`])${CODE_MASK.replace(/[[\]]/g, "\\$&")}\\1`, "g");

/** One action in history.json, with the Playwright code playwright-cli ran for it. */
export interface HistoryAction {
  cmd: string;
  args: string[];
  code: string | null;
}

export interface HistoryStep {
  step: number;
  evaluation_previous_goal: string;
  memory: string;
  next_goal: string;
  actions: HistoryAction[];
  results: string[];
  cost_usd?: number;
  source?: "claude" | "jev";
  jev?: JevRecord | null;
  network?: NetworkEntry[];
  network_errors?: string[];
  console_errors?: string[];
  request_origins?: (string | null)[];
  screenshot?: string;
  screenshot_error?: string;
}

/** The shape of a run's history.json. */
export interface HistoryData {
  task: string;
  task_file: string | null;
  env?: { name: string; path: string };
  success: boolean;
  answer: string;
  steps: number;
  cost_usd: number;
  jev_steps?: number;
  claude_steps?: number;
  video?: string;
  history: HistoryStep[];
}

export class ExportError extends Error {
  exitCode: number;

  constructor(message: string, exitCode: number) {
    super(message);
    this.name = "ExportError";
    this.exitCode = exitCode;
  }
}

const isObject = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

function shapeError(data: unknown): string | null {
  if (!isObject(data)) return "expected a JSON object";
  if (typeof data.task !== "string") return "'task' must be a string";
  if (typeof data.success !== "boolean") return "'success' must be true or false";
  if (!Array.isArray(data.history)) return "'history' must be a list";
  for (const rec of data.history) {
    if (!isObject(rec) || !Array.isArray(rec.actions)) {
      return "each 'history' entry must be an object with an 'actions' list";
    }
    for (const a of rec.actions) {
      if (!isObject(a) || typeof a.cmd !== "string") return "each action must be an object with a string 'cmd'";
      if (a.code != null && typeof a.code !== "string") return "an action's 'code' must be a string or null";
    }
  }
  return null;
}

function isDir(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/** Read a run's history.json. `p` is the run directory or the file itself. */
export function loadHistory(p: string): { runDir: string; data: HistoryData } {
  const file = isDir(p) ? path.join(p, "history.json") : p;
  let data: unknown;
  try {
    const text = new TextDecoder("utf-8", { fatal: true }).decode(fs.readFileSync(file));
    data = JSON.parse(text);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") throw new ExportError(`history not found: ${file}`, 2);
    throw new ExportError(`cannot read ${file}: ${(e as Error).message}`, 2);
  }
  const err = shapeError(data);
  if (err) throw new ExportError(`not a duckwright history: ${file}: ${err}`, 2);
  return { runDir: path.dirname(file), data: data as HistoryData };
}

/** Render a successful run as a @playwright/test spec. */
export function renderSpec(data: HistoryData): { spec: string; warnings: string[] } {
  if (!data.success) throw new ExportError("run did not succeed; only successful runs can be exported", 1);
  const tabs: string[] = [];
  const warnings: string[] = [];
  // Per history step: lines to run before its actions (the waitForResponse arms of the next
  // step's expect-requests, which must exist before the request is made) and its own lines.
  const arms: string[][] = data.history.map(() => []);
  const lines: string[][] = data.history.map(() => []);
  let requests = 0;
  let firstUi: number | null = null;
  let setups = 0;
  let hasCode = false;
  let asserted = false;
  let usesTotp = false;
  const manual: string[] = [];
  for (const [index, rec] of data.history.entries()) {
    const results: unknown[] = Array.isArray(rec.results) ? rec.results : [];
    for (const [i, a] of rec.actions.entries()) {
      const { cmd, code } = a;
      const result = i < results.length ? results[i] : "";
      if (cmd === "request") {
        const passed = typeof code === "string" && code.trim() !== "";
        if (!passed) {
          if (typeof result === "string" && result.startsWith("error:")) {
            warnings.push(`request in step ${index + 1} failed and was skipped`);
          }
          continue;
        }
        const args = Array.isArray(a.args) ? a.args : [];
        const bad = checkRequestCallArgs(args);
        const origin = rec.request_origins?.[i];
        const status = (args[3] ?? "") !== "" ? args[3] : /^ok (\d{3})/.exec(String(result))?.[1];
        if (bad !== null) {
          warnings.push(`request with invalid arguments skipped: ${bad}`);
        } else if (typeof origin !== "string") {
          warnings.push(`request in step ${index + 1} has no recorded origin; skipped`);
        } else if (status === undefined) {
          warnings.push(`request in step ${index + 1} has no recorded status; skipped`);
        } else {
          if (firstUi !== null) {
            throw new ExportError(
              `request in step ${index + 1} comes after a UI action in step ${firstUi}; move it before the first UI action or remove it`, 1);
          }
          const body = args[2] ?? "";
          if (body !== "" && redactBody(body, "application/json") !== body) {
            warnings.push(`request in step ${index + 1} has a body; check it for secrets before committing`);
          }
          lines[index].push(...renderRequestSetup(args, origin, status, ++setups).map((line) => `  ${line}`));
          hasCode = true;
        }
        continue;
      }
      if (cmd === "twofa") {
        const args = Array.isArray(a.args) ? a.args : [];
        const kind = args[0];
        if (result !== "ok") {
          if (typeof result === "string" && result.startsWith("error:")) {
            warnings.push(`twofa in step ${index + 1} failed and was skipped`);
          }
          continue;
        }
        if (firstUi === null) firstUi = index + 1;
        const recorded = typeof code === "string" ? code : "";
        if (kind !== "passkey" && recorded.trim() === "") {
          throw new ExportError(`twofa in step ${index + 1} has no recorded code to replay`, 1);
        }
        if (kind === "totp") {
          const filled = recorded.replace(MASKED_CODE, "totp()");
          if (!filled.includes("totp()")) {
            throw new ExportError(`twofa in step ${index + 1} has no recorded code to replay`, 1);
          }
          lines[index].push(...splitLines(filled).map((line) => `  ${line.includes("totp()") ? `${line} // 2FA` : line}`));
          usesTotp = true;
        } else if (kind === "sms" || kind === "email" || kind === "passkey") {
          lines[index].push(
            kind === "passkey" ? "  // MANUAL: approve the passkey prompt" : `  // MANUAL: enter the ${kind} code here`,
            "  await page.pause();",
          );
          manual.push(`twofa ${kind} in step ${index + 1} is a manual step; the test cannot run unattended`);
        } else {
          continue;
        }
        hasCode = true;
        continue;
      }
      if (firstUi === null && UI_COMMANDS.has(cmd) && result === "ok") firstUi = index + 1;
      if (TAB_COMMANDS.has(cmd)) {
        if (result === "ok") {
          // Command name only: args could break out of the comment.
          lines[index].push(`  // TODO(duckwright): ${cmd} needs a hand edit; this test assumes a single page`);
          if (!tabs.includes(cmd)) tabs.push(cmd);
        }
        continue;
      }
      if (typeof code !== "string" || !code.trim() || cmd === "screenshot") continue;
      if (cmd === "expect-request") {
        // The recorded code is only the "passed" marker: the arm and check are re-rendered here.
        const args = Array.isArray(a.args) ? a.args : [];
        const bad = checkRequestArgs(args);
        if (bad !== null) {
          warnings.push(`expect-request with invalid arguments skipped: ${bad}`);
        } else if (index === 0) {
          warnings.push(`expect-request in step ${index + 1} has no earlier step to arm; skipped`);
        } else {
          const { arm, check } = renderRequestExpect(args, ++requests);
          arms[index - 1].push(`  ${arm}`);
          lines[index].push(...check.map((line) => `  ${line}`));
          hasCode = true;
          asserted = true;
        }
        continue;
      }
      lines[index].push(...splitLines(code).map((line) => `  ${line}`));
      hasCode = true;
      asserted ||= cmd === "expect";
    }
  }
  const body = data.history.flatMap((_, index) => [...arms[index], ...lines[index]]);
  if (!hasCode) throw new ExportError("nothing to export: the run recorded no Playwright code", 1);
  warnings.unshift(...tabs.map((t) => `run used ${t}; edit the test by hand, it assumes a single page`));
  if (setups > 0) warnings.push(COOKIES_NOTE);
  if (!asserted) warnings.push(NO_ASSERTIONS);
  warnings.push(...manual);
  const head = HEADER + (manual.length > 0 ? MANUAL_NOTE : "") + (usesTotp ? `${TOTP_IMPORT}\n${TOTP_HELPER}` : "");
  const spec = head + "\n"
    + `test(${JSON.stringify(data.task)}, async ({ page }) => {\n`
    + body.map((line) => line + "\n").join("")
    + "});\n";
  return { spec, warnings };
}

/** Write the spec for a run. Returns the written path and any warnings. */
export function exportRun(p: string, out: string | null = null, api = false): { path: string; warnings: string[] } {
  const { runDir, data } = loadHistory(p);
  const { spec, warnings } = api ? renderApiSpec(data, runDir) : renderSpec(data);
  const target = out ?? path.join(runDir, api ? API_SPEC_NAME : SPEC_NAME);
  if (resolvePath(target) === resolvePath(path.join(runDir, "history.json"))) {
    throw new ExportError(`refusing to overwrite the run's history: ${target}`, 2);
  }
  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, spec, "utf8");
  } catch (e) {
    throw new ExportError(`cannot write ${target}: ${(e as Error).message}`, 2);
  }
  return { path: target, warnings };
}
