import fs from "node:fs";
import path from "node:path";

import { splitLines } from "./text.ts";

export const SPEC_NAME = "duckwright.spec.ts";
export const HEADER = "// Generated by duckwright from history.json. Review before committing:\n"
  + "// recorded code contains everything the agent typed, passwords included.\n"
  + "import { test, expect } from '@playwright/test';\n";
export const TAB_COMMANDS: ReadonlySet<string> = new Set(["tab-new", "tab-select", "tab-close"]);
export const NO_ASSERTIONS = "no assertions recorded; add expect(...) lines by hand";

/** One action in history.json, with the Playwright code playwright-cli ran for it. */
export interface HistoryAction {
  cmd: string;
  args: string[];
  code: string | null;
}

export interface HistoryStep {
  step: number;
  evaluation_previous_goal: string;
  memory: string;
  next_goal: string;
  actions: HistoryAction[];
  results: string[];
}

/** The shape of a run's history.json. */
export interface HistoryData {
  task: string;
  task_file: string | null;
  success: boolean;
  answer: string;
  steps: number;
  cost_usd: number;
  history: HistoryStep[];
}

export class ExportError extends Error {
  exitCode: number;

  constructor(message: string, exitCode: number) {
    super(message);
    this.name = "ExportError";
    this.exitCode = exitCode;
  }
}

const isObject = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

function shapeError(data: unknown): string | null {
  if (!isObject(data)) return "expected a JSON object";
  if (typeof data.task !== "string") return "'task' must be a string";
  if (typeof data.success !== "boolean") return "'success' must be true or false";
  if (!Array.isArray(data.history)) return "'history' must be a list";
  for (const rec of data.history) {
    if (!isObject(rec) || !Array.isArray(rec.actions)) {
      return "each 'history' entry must be an object with an 'actions' list";
    }
    for (const a of rec.actions) {
      if (!isObject(a) || typeof a.cmd !== "string") return "each action must be an object with a string 'cmd'";
      if (a.code != null && typeof a.code !== "string") return "an action's 'code' must be a string or null";
    }
  }
  return null;
}

function isDir(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/** Read a run's history.json. `p` is the run directory or the file itself. */
export function loadHistory(p: string): { runDir: string; data: HistoryData } {
  const file = isDir(p) ? path.join(p, "history.json") : p;
  let data: unknown;
  try {
    const text = new TextDecoder("utf-8", { fatal: true }).decode(fs.readFileSync(file));
    data = JSON.parse(text);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") throw new ExportError(`history not found: ${file}`, 2);
    throw new ExportError(`cannot read ${file}: ${(e as Error).message}`, 2);
  }
  const err = shapeError(data);
  if (err) throw new ExportError(`not a duckwright history: ${file}: ${err}`, 2);
  return { runDir: path.dirname(file), data: data as HistoryData };
}

/** Render a successful run as a @playwright/test spec. */
export function renderSpec(data: HistoryData): { spec: string; warnings: string[] } {
  if (!data.success) throw new ExportError("run did not succeed; only successful runs can be exported", 1);
  const body: string[] = [];
  const tabs: string[] = [];
  let hasCode = false;
  let asserted = false;
  for (const rec of data.history) {
    const results: unknown[] = Array.isArray(rec.results) ? rec.results : [];
    for (const [i, a] of rec.actions.entries()) {
      const { cmd, code } = a;
      const result = i < results.length ? results[i] : "";
      if (TAB_COMMANDS.has(cmd)) {
        if (result === "ok") {
          // Command name only: args could break out of the comment.
          body.push(`  // TODO(duckwright): ${cmd} needs a hand edit; this test assumes a single page`);
          if (!tabs.includes(cmd)) tabs.push(cmd);
        }
        continue;
      }
      if (typeof code !== "string" || !code.trim() || cmd === "screenshot") continue;
      body.push(...splitLines(code).map((line) => `  ${line}`));
      hasCode = true;
      asserted ||= cmd === "expect";
    }
  }
  if (!hasCode) throw new ExportError("nothing to export: the run recorded no Playwright code", 1);
  const warnings = tabs.map((t) => `run used ${t}; edit the test by hand, it assumes a single page`);
  if (!asserted) warnings.push(NO_ASSERTIONS);
  const spec = HEADER + "\n"
    + `test(${JSON.stringify(data.task)}, async ({ page }) => {\n`
    + body.map((line) => line + "\n").join("")
    + "});\n";
  return { spec, warnings };
}

/** Where a path ends up on disk: symlinks followed as far as they exist, like Python's resolve(). */
function realish(p: string): string {
  const abs = path.resolve(p);
  try {
    return fs.realpathSync(abs);
  } catch {
    const parent = path.dirname(abs);
    return parent === abs ? abs : path.join(realish(parent), path.basename(abs));
  }
}

/** Write the spec for a run. Returns the written path and any warnings. */
export function exportRun(p: string, out: string | null = null): { path: string; warnings: string[] } {
  const { runDir, data } = loadHistory(p);
  const { spec, warnings } = renderSpec(data);
  const target = out ?? path.join(runDir, SPEC_NAME);
  if (realish(target) === realish(path.join(runDir, "history.json"))) {
    throw new ExportError(`refusing to overwrite the run's history: ${target}`, 2);
  }
  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, spec, "utf8");
  } catch (e) {
    throw new ExportError(`cannot write ${target}: ${(e as Error).message}`, 2);
  }
  return { path: target, warnings };
}
