import fs from "node:fs";
import path from "node:path";

import { ExportError } from "./export.ts";
import type { HistoryData } from "./export.ts";
import { networkDir } from "./network.ts";
import type { Header, NetworkEntry } from "./network.ts";
import { REDACTED } from "./redact.ts";

export const API_HEADER = "// Generated by duckwright from history.json and network/. Review before committing:\n"
  + "// captured URLs, headers and bodies are redacted, so secrets appear as [REDACTED].\n"
  + "// For a run that used --state, add test.use({ storageState: 'auth.json' }) to send its cookies.\n"
  + "import { test, expect } from '@playwright/test';\n";

const API_TYPES: ReadonlySet<string> = new Set(["fetch", "xhr"]);
const KEEP_HEADERS: ReadonlySet<string> = new Set(["content-type", "accept"]);

function readText(file: string): string | null {
  try {
    return fs.readFileSync(file, "utf8");
  } catch {
    return null;
  }
}

function readHeaders(file: string): Header[] | null {
  const text = readText(file);
  if (text === null) return null;
  try {
    const h = (JSON.parse(text) as { headers?: unknown }).headers;
    return Array.isArray(h) ? (h as Header[]).filter((x) => typeof x?.name === "string" && typeof x?.value === "string") : [];
  } catch {
    return null;
  }
}

/** Render a successful run's captured API calls as a @playwright/test spec using `request`. */
export function renderApiSpec(data: HistoryData, runDir: string): { spec: string; warnings: string[] } {
  if (!data.success) throw new ExportError("run did not succeed; only successful runs can be exported", 1);
  const warnings: string[] = [];
  const body: string[] = [];
  let n = 0;
  let authRedacted = false;
  for (const rec of data.history) {
    for (const en of (rec.network ?? []) as NetworkEntry[]) {
      if (en.type === null || !API_TYPES.has(en.type)) continue;
      if (en.status === null) {
        warnings.push(`call ${en.id} ${en.method} failed in the capture; skipped`);
        continue;
      }
      const dir = path.join(networkDir(runDir), en.id);
      const all = readHeaders(path.join(dir, "request.json"));
      if (all === null) warnings.push(`call ${en.id}: request.json unreadable; exported without headers`);
      const headers = (all ?? []).filter((h) => KEEP_HEADERS.has(h.name.toLowerCase()));
      if ((all ?? []).some((h) => h.value === REDACTED)) authRedacted = true;
      const text = readText(path.join(dir, "request-body.txt"));
      if (en.url.includes(REDACTED)) warnings.push(`call ${en.id}: url contains ${REDACTED}; fix it by hand`);
      if (text?.includes(REDACTED)) warnings.push(`call ${en.id}: body contains ${REDACTED}; fix it by hand`);
      let data_: string | null = null;
      if (text !== null && text !== "") {
        const json = headers.some((h) => h.name.toLowerCase() === "content-type" && /json/i.test(h.value));
        try {
          data_ = json ? JSON.stringify(JSON.parse(text)) : JSON.stringify(text);
        } catch {
          data_ = JSON.stringify(text);
        }
      }
      n++;
      body.push(
        `  const res${n} = await request.fetch(${JSON.stringify(en.url)}, {`,
        `    method: ${JSON.stringify(en.method.toUpperCase())},`,
      );
      if (headers.length) {
        body.push(`    headers: ${JSON.stringify(Object.fromEntries(headers.map((h) => [h.name.toLowerCase(), h.value])))},`);
      }
      if (data_ !== null) body.push(`    data: ${data_},`);
      body.push("  });", `  expect(res${n}.status()).toBe(${en.status});`);
    }
  }
  if (n === 0) {
    throw new ExportError("nothing to export: no API calls were captured (was the run made with --no-network?)", 1);
  }
  if (authRedacted) warnings.push("some request headers were redacted (auth); add them to the test by hand");
  const spec = API_HEADER + "\n"
    + `test(${JSON.stringify(`${data.task} (API)`)}, async ({ request }) => {\n`
    + body.map((l) => l + "\n").join("")
    + "});\n";
  return { spec, warnings };
}
