import json
from pathlib import Path

SPEC_NAME = "duckwright.spec.ts"
HEADER = (
    "// Generated by duckwright from history.json. Review before committing:\n"
    "// recorded code contains everything the agent typed, passwords included.\n"
    "import { test, expect } from '@playwright/test';\n"
)
TAB_COMMANDS = frozenset({"tab-new", "tab-select", "tab-close"})
NO_ASSERTIONS = "no assertions recorded; add expect(...) lines by hand"


class ExportError(Exception):
    def __init__(self, message: str, exit_code: int):
        super().__init__(message)
        self.exit_code = exit_code


def _shape_error(data) -> str | None:
    if not isinstance(data, dict):
        return "expected a JSON object"
    if not isinstance(data.get("task"), str):
        return "'task' must be a string"
    if not isinstance(data.get("success"), bool):
        return "'success' must be true or false"
    history = data.get("history")
    if not isinstance(history, list):
        return "'history' must be a list"
    for rec in history:
        if not isinstance(rec, dict) or not isinstance(rec.get("actions"), list):
            return "each 'history' entry must be an object with an 'actions' list"
        if not all(isinstance(a, dict) for a in rec["actions"]):
            return "each action must be an object"
    return None


def load_history(path: Path) -> tuple[Path, dict]:
    """Read a run's history.json. `path` is the run directory or the file itself."""
    path = Path(path)
    file = path / "history.json" if path.is_dir() else path
    try:
        data = json.loads(file.read_text())
    except FileNotFoundError:
        raise ExportError(f"history not found: {file}", 2) from None
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as e:
        raise ExportError(f"cannot read {file}: {e}", 2) from None
    err = _shape_error(data)
    if err:
        raise ExportError(f"not a duckwright history: {file}: {err}", 2)
    return file.parent, data


def render_spec(data: dict) -> tuple[str, list[str]]:
    """Render a successful run as a @playwright/test spec. Returns (text, warnings)."""
    if not data["success"]:
        raise ExportError("run did not succeed; only successful runs can be exported", 1)
    body: list[str] = []
    tabs: list[str] = []
    has_code = asserted = False
    for rec in data["history"]:
        results = rec.get("results")
        results = results if isinstance(results, list) else []
        for i, a in enumerate(rec["actions"]):
            cmd, code = a.get("cmd"), a.get("code")
            result = results[i] if i < len(results) else ""
            if cmd in TAB_COMMANDS:
                if result == "ok":
                    # Command name only: args could break out of the comment.
                    body.append(
                        f"  // TODO(duckwright): {cmd} needs a hand edit; "
                        "this test assumes a single page"
                    )
                    if cmd not in tabs:
                        tabs.append(cmd)
                continue
            if not isinstance(code, str) or not code or cmd == "screenshot":
                continue
            body.extend(f"  {line}" for line in code.splitlines())
            has_code = True
            asserted = asserted or cmd == "expect"
    if not has_code:
        raise ExportError("nothing to export: the run recorded no Playwright code", 1)
    warnings = [f"run used {t}; edit the test by hand, it assumes a single page" for t in tabs]
    if not asserted:
        warnings.append(NO_ASSERTIONS)
    title = json.dumps(data["task"], ensure_ascii=False)
    spec = (
        HEADER
        + "\n"
        + f"test({title}, async ({{ page }}) => {{\n"
        + "".join(line + "\n" for line in body)
        + "});\n"
    )
    return spec, warnings


def export_run(path: Path, out: Path | None = None) -> tuple[Path, list[str]]:
    """Write the spec for a run. Returns the written path and any warnings."""
    run_dir, data = load_history(path)
    spec, warnings = render_spec(data)
    target = Path(out) if out is not None else run_dir / SPEC_NAME
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(spec)
    except OSError as e:
        raise ExportError(f"cannot write {target}: {e}", 2) from None
    return target, warnings
