// Generated by duckwright from history.json. Review before committing:
// recorded code contains everything the agent typed, passwords included.
import { test, expect } from '@playwright/test';

test("greet", async ({ page }) => {
  await page.goto('https://example.com/form');
  await page.getByRole('textbox', { name: 'Name' }).fill('Linh');
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByText('Hello, Linh!')).toHaveText("Hello, Linh!");
});
